[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd client && npm install",
  "cd ../server && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cd ..",
  "mkdir -p server/public",
  "cp -r client/dist/* server/public/",
  "cd server && npm run build"
]

[start]
cmd = "cd server && npx prisma migrate deploy && node dist/index.js" 