[build]
builder = "DOCKERFILE"
watchPatterns = ["server/**/*"]

[deploy]
startCommand = "cd server && npx prisma migrate deploy && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "8000" 