[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --include=dev && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 