[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"
watchPatterns = ["server/**/*"]

[deploy]
startCommand = "cd server && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "8000" 