[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build && mkdir -p /app/server && cp -r . /app/server/ && npm prune --production"

[deploy]
startCommand = "cd /app/server && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 